In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('cars_details_merges.csv')

/tmp/ipykernel_21384/999506015.py:1: DtypeWarning: Columns (25,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cars_details_merges.csv')

In [ ]:
df.columns

Index(['position', 'loc', 'myear', 'bt', 'tt', 'ft', 'km', 'ip', 'pi',
       'images',
       ...
       'owner_type', 'price_segment_new', 'template_name_new', 'page_template',
       'template_Type_new', 'experiment', 'Fuel Suppy System',
       'Compression Ratio', 'Alloy Wheel Size', 'Ground Clearance Unladen'],
      dtype='object', length=140)

In [ ]:
df.shape

(37814, 140)

In [ ]:
df = df.loc[:, ['myear', 'bt', 'tt', 'ft', 'price', 'Displacement', 'Max Power', 'No of Cylinder', 'Seating Capacity', 'model_name','brand_name', 'km_driven', 'city_name_new', 'Drive Type']]

In [ ]:
df.shape

(37814, 14)

In [ ]:
df = df.rename(columns = ({'myear' : 'year', 'bt' : 'type', 'tt' : 'transmission', 'ft' : 'fuel', 'km_driven' : 'odometer', 'Displacement' : 'engine_cc', 'Max Power' : 'max_power', 'No of Cylinder' : 'cylinders', 'Seating Capacity' : 'seats', 'model_name' : 'model', 'city_name_new' : 'region', 'brand_name' : 'manufacturer', 'Drive Type' : 'drive'}))

In [ ]:
df.head()

,year,type,transmission,fuel,price,engine_cc,max_power,cylinders,seats,model,manufacturer,odometer,region,drive
0,2016,Hatchback,Manual,CNG,₹ 3.70 Lakh,998.0,58.16bhp@6200rpm,3.0,5.0,maruti wagon r,maruti,69162,lucknow,FWD
1,2015,Hatchback,Manual,CNG,₹ 3.65 Lakh,998.0,58.2bhp@6000rpm,3.0,5.0,maruti celerio,maruti,45864,mumbai,FWD
2,2015,Sedan,Manual,CNG,₹ 4.21 Lakh,1198.0,86.7bhp@6000rpm,4.0,5.0,honda amaze,honda,81506,new delhi,FWD
3,2013,Hatchback,Manual,CNG,₹ 2.40 Lakh,998.0,58.2bhp@6200rpm,3.0,5.0,maruti wagon r,maruti,115893,new delhi,FWD
4,2022,MUV,Manual,CNG,₹ 11.75 Lakh,1462.0,86.63bhp@5500rpm,4.0,7.0,maruti ertiga,maruti,18900,mumbai,2WD

In [ ]:
df['type'] = df['type'].str.lower()

In [ ]:
df['transmission'] = df['transmission'].str.lower()

In [ ]:
df['fuel'] = df['fuel'].str.lower()

In [ ]:
df['price'] = df['price'].str.split(' ').str.get(1)

In [ ]:
df['price'].isnull().sum()

np.int64(0)

In [ ]:
df[df['price'] == 0]

Empty DataFrame
Columns: [year, type, transmission, fuel, price, engine_cc, max_power, cylinders, seats, model, manufacturer, odometer, region, drive]
Index: []

In [ ]:
df['engine_cc'].isnull().sum()

np.int64(53)

In [ ]:
df['max_power'].isnull().sum()

np.int64(231)

In [ ]:
df['max_power'] = df['max_power'].str.split('bhp').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('Bhp').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split(' @ ').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('hp').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('@').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split(' ').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('BHP').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('ps').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('PS').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('(').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.split('/').str.get(0)

In [ ]:
df['cylinders'].isnull().sum()

np.int64(143)

In [ ]:
df['seats'].isnull().sum()

np.int64(18)

In [ ]:
df.head()

,year,type,transmission,fuel,price,engine_cc,max_power,cylinders,seats,model,manufacturer,odometer,region,drive
0,2016,hatchback,manual,cng,3.70,998.0,58.16,3.0,5.0,maruti wagon r,maruti,69162,lucknow,FWD
1,2015,hatchback,manual,cng,3.65,998.0,58.2,3.0,5.0,maruti celerio,maruti,45864,mumbai,FWD
2,2015,sedan,manual,cng,4.21,1198.0,86.7,4.0,5.0,honda amaze,honda,81506,new delhi,FWD
3,2013,hatchback,manual,cng,2.40,998.0,58.2,3.0,5.0,maruti wagon r,maruti,115893,new delhi,FWD
4,2022,muv,manual,cng,11.75,1462.0,86.63,4.0,7.0,maruti ertiga,maruti,18900,mumbai,2WD

In [ ]:
df['model'].value_counts()

model
honda city            1911
hyundai i20           1501
maruti swift          1440
maruti wagon r        1415
maruti swift dzire    1185
                      ...
maruti alto 2021         1
mahindra willys          1
volkswagen touareg       1
mahindra logan           1
maruti 1000              1
Name: count, Length: 382, dtype: int64

In [ ]:
df['model'] = df.apply(
    lambda x: x['model'].replace(x['manufacturer'], '').strip(),
    axis=1
)

In [ ]:
df['drive'] = df['drive'].str.lower()

In [ ]:
df.head()

,year,type,transmission,fuel,price,engine_cc,max_power,cylinders,seats,model,manufacturer,odometer,region,drive
0,2016,hatchback,manual,cng,3.70,998.0,58.16,3.0,5.0,wagon r,maruti,69162,lucknow,fwd
1,2015,hatchback,manual,cng,3.65,998.0,58.2,3.0,5.0,celerio,maruti,45864,mumbai,fwd
2,2015,sedan,manual,cng,4.21,1198.0,86.7,4.0,5.0,amaze,honda,81506,new delhi,fwd
3,2013,hatchback,manual,cng,2.40,998.0,58.2,3.0,5.0,wagon r,maruti,115893,new delhi,fwd
4,2022,muv,manual,cng,11.75,1462.0,86.63,4.0,7.0,ertiga,maruti,18900,mumbai,2wd

In [ ]:
df['model'].value_counts()

model
city               1911
i20                1501
swift              1440
wagon r            1415
swift dzire        1185
                   ...
scorpio classic       1
willys                1
touareg               1
alto 2021             1
1000                  1
Name: count, Length: 381, dtype: int64

In [ ]:
df['price'].unique()

array(['3.70', '3.65', '4.21', ..., '24.36', '20.56', '21.26'],
      dtype=object)

In [ ]:
import datetime

In [ ]:
x = datetime.datetime.now().year - 1983

In [ ]:
x

43

In [ ]:
df['age'] = datetime.datetime.now().year - df['year']

In [ ]:
df.drop(columns = ['year'], inplace = True)

In [ ]:
df.head()

,type,transmission,fuel,price,engine_cc,max_power,cylinders,seats,model,manufacturer,odometer,region,drive,age
0,hatchback,manual,cng,3.70,998.0,58.16,3.0,5.0,wagon r,maruti,69162,lucknow,fwd,10
1,hatchback,manual,cng,3.65,998.0,58.2,3.0,5.0,celerio,maruti,45864,mumbai,fwd,11
2,sedan,manual,cng,4.21,1198.0,86.7,4.0,5.0,amaze,honda,81506,new delhi,fwd,11
3,hatchback,manual,cng,2.40,998.0,58.2,3.0,5.0,wagon r,maruti,115893,new delhi,fwd,13
4,muv,manual,cng,11.75,1462.0,86.63,4.0,7.0,ertiga,maruti,18900,mumbai,2wd,4

In [ ]:
df['price'] = df['price'].str.replace(',', '')

In [ ]:
df['price'] = df['price'].astype(float)

In [ ]:
df['price'] = df['price'] * 100000

In [ ]:
df.head()

,type,transmission,fuel,price,engine_cc,max_power,cylinders,seats,model,manufacturer,odometer,region,drive,age
0,hatchback,manual,cng,370000.0,998.0,58.16,3.0,5.0,wagon r,maruti,69162,lucknow,fwd,10
1,hatchback,manual,cng,365000.0,998.0,58.2,3.0,5.0,celerio,maruti,45864,mumbai,fwd,11
2,sedan,manual,cng,421000.0,1198.0,86.7,4.0,5.0,amaze,honda,81506,new delhi,fwd,11
3,hatchback,manual,cng,240000.0,998.0,58.2,3.0,5.0,wagon r,maruti,115893,new delhi,fwd,13
4,muv,manual,cng,1175000.0,1462.0,86.63,4.0,7.0,ertiga,maruti,18900,mumbai,2wd,4

In [ ]:
df['max_power'] = df['max_power'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37814 entries, 0 to 37813
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          37795 non-null  object
 1   transmission  37814 non-null  object
 2   fuel          37814 non-null  object
 3   price         37814 non-null  float64
 4   engine_cc     37761 non-null  float64
 5   max_power     37583 non-null  float64
 6   cylinders     37671 non-null  float64
 7   seats         37796 non-null  float64
 8   model         37814 non-null  object
 9   manufacturer  37814 non-null  object
 10  odometer      37814 non-null  int64
 11  region        37814 non-null  object
 12  drive         33318 non-null  object
 13  age           37814 non-null  int64
dtypes: float64(5), int64(2), object(7)
memory usage: 4.0+ MB

In [ ]:
df.to_csv('cardekho_data2.csv', index = False)