In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('cardekho_dataset.csv')

In [ ]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [ ]:
df.shape

(15411, 13)

In [ ]:
df.drop(columns = (['seller_type', 'mileage']), inplace = True)

In [ ]:
df.shape

(15411, 11)

In [ ]:
df.duplicated().sum()

np.int64(195)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(15216, 11)

In [ ]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,fuel_type,transmission_type,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Petrol,Manual,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Petrol,Manual,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Petrol,Manual,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Petrol,Manual,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Diesel,Manual,1498,98.59,5,570000

In [ ]:
df = df.rename(columns = ({'brand' : 'manufacturer', 'vehicle_age' : 'age', 'km_driven' : 'odometer', 'fuel_type' : 'fuel', 'transmission_type' : 'transmission', 'engine' : 'engine_cc', 'selling_price' : 'price'}))

In [ ]:
df.drop(columns = ('car_name'), inplace = True)

In [ ]:
df['manufacturer'] = df['manufacturer'].str.lower()

In [ ]:
df.head()

,manufacturer,model,age,odometer,fuel,transmission,engine_cc,max_power,seats,price
0,maruti,Alto,9,120000,Petrol,Manual,796,46.30,5,120000
1,hyundai,Grand,5,20000,Petrol,Manual,1197,82.00,5,550000
2,hyundai,i20,11,60000,Petrol,Manual,1197,80.00,5,215000
3,maruti,Alto,9,37000,Petrol,Manual,998,67.10,5,226000
4,ford,Ecosport,6,30000,Diesel,Manual,1498,98.59,5,570000

In [ ]:
df['model'] = df['model'].str.lower()

In [ ]:
df['fuel'] = df['fuel'].str.lower()

In [ ]:
df['transmission'] = df['transmission'].str.lower()

In [ ]:
df.shape

(15216, 10)

In [ ]:
df.head()

,manufacturer,model,age,odometer,fuel,transmission,engine_cc,max_power,seats,price
0,maruti,alto,9,120000,petrol,manual,796,46.30,5,120000
1,hyundai,grand,5,20000,petrol,manual,1197,82.00,5,550000
2,hyundai,i20,11,60000,petrol,manual,1197,80.00,5,215000
3,maruti,alto,9,37000,petrol,manual,998,67.10,5,226000
4,ford,ecosport,6,30000,diesel,manual,1498,98.59,5,570000

In [ ]:
df['region'] = np.nan

In [ ]:
df['type'] = np.nan

In [ ]:
df['cylinders'] = np.nan

In [ ]:
df['drive'] = np.nan

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15216 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  15216 non-null  object
 1   model         15216 non-null  object
 2   age           15216 non-null  int64
 3   odometer      15216 non-null  int64
 4   fuel          15216 non-null  object
 5   transmission  15216 non-null  object
 6   engine_cc     15216 non-null  int64
 7   max_power     15216 non-null  float64
 8   seats         15216 non-null  int64
 9   price         15216 non-null  int64
 10  region        0 non-null      float64
 11  type          0 non-null      float64
 12  cylinders     0 non-null      float64
 13  drive         0 non-null      float64
dtypes: float64(5), int64(5), object(4)
memory usage: 1.7+ MB

In [ ]:
df.head()

,manufacturer,model,age,odometer,fuel,transmission,engine_cc,max_power,seats,price,region,type,cylinders,drive
0,maruti,alto,9,120000,petrol,manual,796,46.30,5,120000,NaN,NaN,NaN,NaN
1,hyundai,grand,5,20000,petrol,manual,1197,82.00,5,550000,NaN,NaN,NaN,NaN
2,hyundai,i20,11,60000,petrol,manual,1197,80.00,5,215000,NaN,NaN,NaN,NaN
3,maruti,alto,9,37000,petrol,manual,998,67.10,5,226000,NaN,NaN,NaN,NaN
4,ford,ecosport,6,30000,diesel,manual,1498,98.59,5,570000,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

manufacturer        0
model               0
age                 0
odometer            0
fuel                0
transmission        0
engine_cc           0
max_power           0
seats               0
price               0
region          15216
type            15216
cylinders       15216
drive           15216
dtype: int64

In [ ]:
df.to_csv('cardekho_data_1.csv', index = False)