In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('cars_data_cleaned_1.csv')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.0,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,745000,maruti suzuki,baleno,4.0,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,465000,hyundai,grand i10,3.0,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,546000,maruti suzuki,celerio,3.0,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,428000,hyundai,santro,4.0,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df.shape

(57765, 14)

In [ ]:
df['model'] = df['model'].replace('grand', 'grand i10')

In [ ]:
df.isnull().sum()

region          15063
price               0
manufacturer        0
model               0
cylinders       15293
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['region'] = df.groupby(['manufacturer', 'model'])['region']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))
                #  \ --> it means that code is in continuation

/tmp/ipykernel_2905/4174064319.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df['region'].isnull().sum()

np.int64(713)

In [ ]:
df['region'] = df.groupby(['manufacturer'])['region']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders       15293
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['cylinders'] = df.groupby(['manufacturer', 'model', 'fuel', 'transmission'])['cylinders']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders         941
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['cylinders'] = df.groupby(['manufacturer', 'model', 'fuel'])['cylinders']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders         831
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['cylinders'] = df.groupby(['manufacturer', 'model'])['cylinders']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders         813
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['cylinders'] = df.groupby(['manufacturer'])['cylinders']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['drive'] = df.groupby(['manufacturer', 'model', 'fuel', 'transmission'])['drive']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

/tmp/ipykernel_2905/1576210882.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive            1135
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['cylinders'].value_counts()

cylinders
4.0     43822
3.0     13136
6.0       495
5.0       131
2.0        86
7.0        55
8.0        30
1.0         5
10.0        2
12.0        2
16.0        1
Name: count, dtype: int64

In [ ]:
df['drive'] = df.groupby(['manufacturer', 'model', 'fuel'])['drive']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

/tmp/ipykernel_2905/4222545681.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive             991
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['drive'] = df.groupby(['manufacturer', 'model'])['drive']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

/tmp/ipykernel_2905/3050005452.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive             944
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['drive'] = df.groupby(['manufacturer'])['drive']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

/tmp/ipykernel_2905/1284316986.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive              13
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df[df['drive'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
34042,nashik,200000,mahindra renault,logan,4.0,diesel,110000,manual,NaN,sedan,5.0,1461.0,65.0,19
34043,nashik,199000,mahindra renault,logan,4.0,petrol,70000,manual,NaN,sedan,5.0,1598.0,84.5,17
34044,chennai,145000,mahindra renault,logan,4.0,diesel,82124,manual,NaN,sedan,5.0,1461.0,65.0,16
34045,paratwada,145000,mahindra renault,logan,4.0,diesel,120000,manual,NaN,sedan,5.0,1461.0,65.0,17
34046,pune,119000,mahindra renault,logan,4.0,petrol,53246,manual,NaN,sedan,5.0,1390.0,75.0,18
34047,lucknow,109000,mahindra renault,logan,4.0,diesel,42224,manual,NaN,sedan,5.0,1461.0,65.0,18
34048,jaipur,150000,mahindra renault,logan,4.0,diesel,136776,manual,NaN,sedan,5.0,1461.0,65.0,16
34049,thane,135000,mahindra renault,logan,4.0,petrol,62000,manual,NaN,sedan,5.0,1390.0,76.0,18
34050,pune,200000,mahindra renault,logan,4.0,petrol,47274,manual,NaN,sedan,5.0,1390.0,75.0,17
34051,bangalore,167000,mahindra renault,logan,4.0,petrol,61733,manual,NaN,sedan,5.0,1598.0,84.5,18
34052,hyderabad,150000,mahindra renault,logan,4.0,petrol,72141,manual,NaN,sedan,5.0,1390.0,75.0,18
34053,noida,100000,mahindra renault,logan,4.0,petrol,89842,manual,NaN,sedan,5.0,1598.0,84.5,18
34054,jaipur,100000,mahindra renault,logan,4.0,diesel,126184,manual,NaN,sedan,5.0,1461.0,65.0,18

In [ ]:
df['drive'] = df['drive'].fillna('fwd')

In [ ]:
df.isnull().sum()

region              0
price               0
manufacturer        0
model               0
cylinders           0
fuel                0
odometer            0
transmission        0
drive               0
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['type'].sample(10)

19274          NaN
21738    hatchback
3911     hatchback
3412     hatchback
48407    hatchback
7913           NaN
19523          NaN
52740        sedan
49187        sedan
21737     minivans
Name: type, dtype: object

In [ ]:
df['type'] = df.groupby(['manufacturer', 'model'])['type']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

/tmp/ipykernel_2905/4251093372.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region             0
price              0
manufacturer       0
model              0
cylinders          0
fuel               0
odometer           0
transmission       0
drive              0
type               2
seats           6091
engine_cc       6120
max_power       6258
age                0
dtype: int64

In [ ]:
df[df['type'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
14486,ghaziabad,4500000,lexus,nx,4.0,petrol,44000,automatic,fwd,NaN,5.0,2499.0,194.30,3
34077,jaunpur,300000,others,huracan evo,10.0,petrol,80000,automatic,rwd,NaN,2.0,5204.0,602.11,5

In [ ]:
df[df['manufacturer'] == 'lexus']

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
6707,ghaziabad,4100000,lexus,es,4.0,petrol,34000,automatic,fwd,sedan,5.0,2487.0,214.56,4
14486,ghaziabad,4500000,lexus,nx,4.0,petrol,44000,automatic,fwd,NaN,5.0,2499.0,194.30,3
15236,ghaziabad,4100000,lexus,es,4.0,petrol,33000,automatic,fwd,sedan,5.0,2487.0,214.56,4
17927,ghaziabad,3990000,lexus,es,4.0,petrol,28000,automatic,fwd,sedan,5.0,2487.0,214.56,3
34063,bangalore,185000,lexus,lx,8.0,diesel,60000,automatic,4wd,suv,5.0,4461.0,261.00,8
34064,ghaziabad,4293000,lexus,es,4.0,petrol,27760,automatic,fwd,sedan,5.0,2487.0,214.56,7

In [ ]:
df['model'] = df['model'].replace('vitara', 'vitara brezza').replace('rover', 'range rover')

In [ ]:
df['model'] = df['model'].replace('3', '3 series').replace('5', '5 series').replace('7', '7 series')

In [ ]:
df['model'] = df['model'].replace('kuv', 'kuv100')

In [ ]:
df['model'] = df['model'].replace('6', '6 series')

In [ ]:
df['model'] = df['model'].replace('dzire vxi', 'dzire').replace('dzire zxi', 'dzire').replace('dzire lxi', 'dzire')

In [ ]:
df['model'] = df['model'].replace('xc', 'xc90').replace('xc 90', 'xc90')

In [ ]:
df['model'] = df['model'].replace('cr', 'cr-v').replace('c', 'c-class').replace('eeco cargo', 'eeco').replace('mux', 'mu-x').replace('alturas', 'alturas g4')

In [ ]:
df.loc[df['model'] == 'gtc4lusso', 'type'] = df.loc[df['model'] == 'gtc4lusso', 'type'].fillna('luxury vehicles')

In [ ]:
df.loc[df['model'] == 'ghost', 'type'] = df.loc[df['model'] == 'ghost', 'type'].fillna('sedan')

In [ ]:
# quattroporte
df.loc[df['model'] == 'quattroporte', 'type'] = df.loc[df['model'] == 'quattroporte', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 'cls', 'type'] = df.loc[df['model'] == 'cls', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 'rx', 'type'] = df.loc[df['model'] == 'rx', 'type'].fillna('crossover')

In [ ]:
df['type'].value_counts()

type
hatchback          23608
sedan              15583
suv                14121
muv                 2981
minivans             507
crossover             95
luxury vehicles       73
pickup trucks         53
convertibles          15
coupe                 10
wagon                  6
hybrids                3
mpv                    1
Name: count, dtype: int64

In [ ]:
df['type'] = df['type'].replace('mpv', 'muv')

In [ ]:
df.shape

(57765, 14)

In [ ]:
# df[df['type'].isnull()]
df = df.drop(index = [14486, 34077])

In [ ]:
df.shape

(57763, 14)

In [ ]:
df.isnull().sum()

region             0
price              0
manufacturer       0
model              0
cylinders          0
fuel               0
odometer           0
transmission       0
drive              0
type             709
seats           6091
engine_cc       6120
max_power       6258
age                0
dtype: int64

In [ ]:
df[df['seats'] == 0]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
9280,pune,1.15,honda,city,4.0,petrol,40000,manual,fwd,sedan,0.0,1493.0,100.00,18
18557,hyderabad,11.54,nissan,kicks,4.0,diesel,10000,manual,fwd,suv,0.0,1461.0,108.49,2
23575,hyderabad,0.80,maruti suzuki,omni,3.0,petrol,70000,manual,rwd,minivans,0.0,NaN,NaN,17
23587,bhopal,0.85,maruti suzuki,omni,3.0,petrol,60000,manual,rwd,minivans,0.0,NaN,NaN,18
23593,kolkata,1.20,maruti suzuki,omni,3.0,petrol,70000,manual,rwd,minivans,0.0,NaN,NaN,17
23607,rajkot,1.10,maruti suzuki,omni,3.0,petrol,60000,manual,rwd,minivans,0.0,NaN,NaN,16
23622,jam jodhpur,0.75,maruti suzuki,omni,3.0,petrol,120000,manual,rwd,minivans,0.0,NaN,NaN,33
23627,mandsaur,1.50,maruti suzuki,omni,3.0,petrol,90000,manual,rwd,minivans,0.0,NaN,NaN,16
23632,jamnagar,0.70,maruti suzuki,omni,3.0,petrol,140000,manual,rwd,minivans,0.0,NaN,NaN,18
23646,mandsaur,1.50,maruti suzuki,omni,3.0,petrol,120000,manual,rwd,minivans,0.0,NaN,NaN,15
23649,gorakhpur,1.01,maruti suzuki,omni,3.0,petrol,70000,manual,rwd,minivans,0.0,NaN,NaN,16
23691,jaipur,0.99,maruti suzuki,omni,3.0,petrol,80000,manual,rwd,minivans,0.0,NaN,NaN,15
44467,indore,0.85,tata,indica,4.0,diesel,80000,manual,fwd,hatchback,0.0,1248.0,NaN,16

In [ ]:
df['seats'] = df['seats'].replace(0.0, np.nan)

In [ ]:
df['seats'].isnull().sum()

np.int64(6098)

In [ ]:
df['seats'] = df.groupby(['manufacturer', 'model'])['seats']\
                 .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))

In [ ]:
df.isnull().sum()

region             0
price              0
manufacturer       0
model              0
cylinders          0
fuel               0
odometer           0
transmission       0
drive              0
type               0
seats              0
engine_cc       6120
max_power       6258
age                0
dtype: int64

In [ ]:
df[df['seats'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
14,agra,946000,hyundai,new i20,4.0,petrol,7352,automatic,fwd,hatchback,NaN,NaN,NaN,2
20,agra,884000,hyundai,new i20,4.0,petrol,21606,automatic,fwd,hatchback,NaN,NaN,NaN,3
25,ahmedabad,487910,mahindra,tuv300,3.0,diesel,53365,manual,rwd,suv,NaN,NaN,NaN,10
57,ambala,1029000,maruti suzuki,new ertiga,4.0,petrol,21663,automatic,fwd,muv,NaN,NaN,NaN,4
60,ambala,601000,skoda,rapid new,3.0,petrol,60024,automatic,fwd,sedan,NaN,NaN,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5964,pune,423000,mahindra,kuv100 nxt,3.0,diesel,84803,manual,fwd,crossover,NaN,NaN,NaN,8
6000,pune,289000,maruti suzuki,wagon r 1.0,2.0,petrol,37784,manual,fwd,hatchback,NaN,NaN,NaN,10
6044,visakhapatnam,527000,hyundai,new santro 1.1,4.0,petrol+cng,49650,manual,fwd,hatchback,NaN,NaN,NaN,4
6053,visakhapatnam,882000,maruti suzuki,s-cross,4.0,petrol,58665,automatic,fwd,suv,NaN,NaN,NaN,5
6054,visakhapatnam,1052323,maruti suzuki,jimny,4.0,petrol,13647,automatic,4wd,suv,NaN,NaN,NaN,3

In [ ]:
df['model'] = df['model'].str.strip()

In [ ]:
df[df['model'] == 'polo']

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
182,bangalore,460000,volkswagen,polo,3.0,petrol,124416,manual,fwd,hatchback,5.0,NaN,NaN,11
400,bangalore,542000,volkswagen,polo,3.0,petrol,74539,manual,fwd,hatchback,5.0,NaN,NaN,8
477,bangalore,590000,volkswagen,polo,3.0,petrol,71311,manual,fwd,hatchback,5.0,NaN,NaN,6
481,bangalore,480000,volkswagen,polo,3.0,petrol,50699,manual,fwd,hatchback,5.0,NaN,NaN,10
490,bangalore,388000,volkswagen,polo,3.0,petrol,68274,manual,fwd,hatchback,5.0,NaN,NaN,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41849,dehradun,550000,volkswagen,polo,3.0,petrol,48141,manual,fwd,hatchback,5.0,999.0,75.0,7
42174,rajkot,297000,volkswagen,polo,3.0,petrol,157151,manual,fwd,hatchback,5.0,1198.0,74.0,12
42490,surat,477000,volkswagen,polo,3.0,petrol,75682,manual,fwd,hatchback,5.0,1199.0,74.0,10
42736,surat,454000,volkswagen,polo,3.0,petrol,23677,manual,fwd,hatchback,5.0,1199.0,74.0,10
43727,indore,375000,volkswagen,polo,3.0,diesel,62000,manual,fwd,hatchback,5.0,1199.0,73.9,13

In [ ]:
df['model'] = df['model'].replace('tuv300', 'tuv 300').replace('new i20', 'i20').replace('new ertiga', 'ertiga').replace('kuv100 nxt', 'kuv100').replace('kuv 100', 'kuv100').replace('new rapid', 'rapid').replace('new santro 1.1', 'santro').replace('wagon r 1.0', 'wagon r')

In [ ]:
df.loc[df['model'] == 's-cross', 'seats'] = df.loc[df['model'] == 's-cross', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'jimny', 'seats'] = df.loc[df['model'] == 'jimny', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'curvv', 'seats'] = df.loc[df['model'] == 'curvv', 'seats'].fillna(5)

In [ ]:
df['model'] = df['model'].replace('rapid new', 'rapid').replace('figo aspire', 'figo').replace('xuv 300', 'xuv300')

In [ ]:
df.loc[df['model'] == 'urban cruiser hyryder', 'seats'] = df.loc[df['model'] == 'urban cruiser hyryder', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'exter', 'seats'] = df.loc[df['model'] == 'exter', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'fronx', 'seats'] = df.loc[df['model'] == 'fronx', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'thar roxx', 'seats'] = df.loc[df['model'] == 'thar roxx', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'tiago jtp', 'seats'] = df.loc[df['model'] == 'tiago jtp', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'elevate', 'seats'] = df.loc[df['model'] == 'elevate', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'creta n-line', 'seats'] = df.loc[df['model'] == 'creta n-line', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'syros', 'seats'] = df.loc[df['model'] == 'syros', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'xuv 3xo', 'seats'] = df.loc[df['model'] == 'xuv 3xo', 'seats'].fillna(5)

In [ ]:
df.loc[df['model'] == 'countryman', 'seats'] = df.loc[df['model'] == 'countryman', 'seats'].fillna(5)

In [ ]:
df['model'] = df['model'].replace('wagon r 1.2', 'wagon r').replace('fluidic verna 4s', 'verna').replace('b-class', 'b class')

In [ ]:
df['model'] = df['model'].replace('cross polo', 'polo')

In [ ]:
df.loc[df['model'] == 'venue n-line', 'seats'] = df.loc[df['model'] == 'venue n-line', 'seats'].fillna(5)

In [ ]:
df[df['engine_cc'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,5.12,tata,tiago,3.0,petrol,20979,manual,fwd,hatchback,5.0,NaN,NaN,5
1,agra,7.45,maruti suzuki,baleno,4.0,petrol,20176,manual,fwd,hatchback,5.0,NaN,NaN,3
2,agra,4.65,hyundai,grand i10,3.0,cng,41448,manual,fwd,hatchback,5.0,NaN,NaN,7
3,agra,5.46,maruti suzuki,celerio,3.0,petrol,8527,manual,fwd,hatchback,5.0,NaN,NaN,3
4,agra,4.28,hyundai,santro,4.0,cng,102049,manual,fwd,hatchback,5.0,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47411,bangalore,2.00,honda,city,4.0,petrol,51259,manual,fwd,sedan,5.0,NaN,NaN,20
50045,mumbai,7.80,honda,city,4.0,petrol,58871,automatic,fwd,sedan,5.0,NaN,NaN,10
50046,mumbai,5.90,honda,city,4.0,petrol,55000,automatic,fwd,sedan,5.0,NaN,NaN,11
50091,mumbai,1.25,honda,city,4.0,petrol,57788,manual,fwd,sedan,5.0,NaN,NaN,22
56032,new delhi,1.30,honda,city,4.0,petrol,110000,manual,fwd,sedan,5.0,NaN,NaN,22

In [ ]:
df['engine_cc'] = df.groupby(['manufacturer','model'])['engine_cc']\
                   .transform(lambda x: x.fillna(x.median()))

In [ ]:
# df['engine_cc'] = pd.to_numeric(df['engine_cc'], errors='coerce')

In [ ]:
df['engine_cc'] = df['engine_cc'].fillna(df['engine_cc'].median())

In [ ]:
df.isnull().sum()

region             0
price              0
manufacturer       0
model              0
cylinders          0
fuel               0
odometer           0
transmission       0
drive              0
type               0
seats              0
engine_cc          0
max_power       6258
age                0
dtype: int64

In [ ]:
df['engine_cc'].sample(20)

17182    1197.0
54651    1396.0
52836     998.0
48523     998.0
11619    1248.0
38904    1086.0
46806    1199.0
45886    1120.0
47743    1248.0
2694     1199.0
51719    1120.0
6934     1248.0
29081     936.0
987      1197.0
44775     998.0
33375    1368.0
26376    1198.0
6074     1197.0
48674     814.0
36559     998.0
Name: engine_cc, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57763 entries, 0 to 57764
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        57763 non-null  object
 1   price         57763 non-null  int64
 2   manufacturer  57763 non-null  object
 3   model         57763 non-null  object
 4   cylinders     57763 non-null  float64
 5   fuel          57763 non-null  object
 6   odometer      57763 non-null  int64
 7   transmission  57763 non-null  object
 8   drive         57763 non-null  object
 9   type          57763 non-null  object
 10  seats         57763 non-null  float64
 11  engine_cc     57763 non-null  float64
 12  max_power     51505 non-null  float64
 13  age           57763 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 6.6+ MB

In [ ]:
df['engine_cc'] = df['engine_cc'].astype('int')

In [ ]:
df[df['max_power'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.0,petrol,20979,manual,fwd,hatchback,5.0,1199,NaN,5
1,agra,745000,maruti suzuki,baleno,4.0,petrol,20176,manual,fwd,hatchback,5.0,1197,NaN,3
2,agra,465000,hyundai,grand i10,3.0,cng,41448,manual,fwd,hatchback,5.0,1197,NaN,7
3,agra,546000,maruti suzuki,celerio,3.0,petrol,8527,manual,fwd,hatchback,5.0,998,NaN,3
4,agra,428000,hyundai,santro,4.0,cng,102049,manual,fwd,hatchback,5.0,1086,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54875,new delhi,125000,honda,cr-v,4.0,petrol,80000,manual,fwd,suv,5.0,1997,NaN,18
54889,noida,300000,honda,cr-v,4.0,petrol,110000,manual,fwd,suv,5.0,1198,NaN,18
54897,new delhi,130000,honda,city,4.0,petrol,110000,manual,fwd,sedan,5.0,1497,NaN,22
56549,pune,105000,maruti suzuki,estilo,4.0,petrol,70000,manual,fwd,hatchback,5.0,1061,NaN,17
57028,pune,335000,maruti suzuki,swift,4.0,diesel,99000,manual,fwd,hatchback,5.0,1248,NaN,15

In [ ]:
df['max_power'] = df.groupby('engine_cc')['max_power'].transform(
    lambda x: x.fillna(x.median())
)

In [ ]:
df.isnull().sum()

region           0
price            0
manufacturer     0
model            0
cylinders        0
fuel             0
odometer         0
transmission     0
drive            0
type             0
seats            0
engine_cc        0
max_power       94
age              0
dtype: int64

In [ ]:
df['max_power'] = df['max_power'].fillna(df['max_power'].median())

In [ ]:
df.isnull().sum()

region          0
price           0
manufacturer    0
model           0
cylinders       0
fuel            0
odometer        0
transmission    0
drive           0
type            0
seats           0
engine_cc       0
max_power       0
age             0
dtype: int64

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.0,petrol,20979,manual,fwd,hatchback,5.0,1199,84.88,5
1,agra,745000,maruti suzuki,baleno,4.0,petrol,20176,manual,fwd,hatchback,5.0,1197,81.86,3
2,agra,465000,hyundai,grand i10,3.0,cng,41448,manual,fwd,hatchback,5.0,1197,81.86,7
3,agra,546000,maruti suzuki,celerio,3.0,petrol,8527,manual,fwd,hatchback,5.0,998,67.04,3
4,agra,428000,hyundai,santro,4.0,cng,102049,manual,fwd,hatchback,5.0,1086,68.05,5

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('cars_missing_value_imputed.csv', index = False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58914 entries, 0 to 58913
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        58914 non-null  object
 1   price         58914 non-null  float64
 2   manufacturer  58914 non-null  object
 3   model         58914 non-null  object
 4   cylinders     58914 non-null  float64
 5   fuel          58914 non-null  object
 6   odometer      58914 non-null  int64
 7   transmission  58914 non-null  object
 8   drive         58914 non-null  object
 9   type          58914 non-null  object
 10  seats         58914 non-null  float64
 11  engine_cc     58914 non-null  int64
 12  max_power     58914 non-null  float64
 13  age           58914 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 6.3+ MB