In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('cars_data.csv')

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
df.duplicated().sum()

np.int64(191)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(58914, 14)

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,"512,000.00",tata,tiago,3.00,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,"745,000.00",maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,"465,000.00",hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,"546,000.00",maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,"428,000.00",hyundai,santro,4.00,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df.isnull().sum()

region          15216
price               0
manufacturer        0
model               0
cylinders       15456
fuel                0
odometer            0
transmission        0
drive           19889
type            15234
seats            6093
engine_cc        6128
max_power        6305
age                 0
dtype: int64

In [ ]:
325000 / 100000

3.25

In [ ]:
df['price'] = df['price'].astype(str).str.replace(',', '')

In [ ]:
def clean_price(x):

    x = float(x)

    if x > 1000:   # price written in rupees
        return x / 100000

    else:          # already in lakhs
        return x

In [ ]:
df['price'] = df['price'].apply(clean_price)

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.00,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,745000,maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,465000,hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,546000,maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,428000,hyundai,santro,4.00,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df['price'] = df['price'].astype(float).astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58914 entries, 0 to 59104
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        43698 non-null  object
 1   price         58914 non-null  int64
 2   manufacturer  58914 non-null  object
 3   model         58914 non-null  object
 4   cylinders     43458 non-null  float64
 5   fuel          58914 non-null  object
 6   odometer      58914 non-null  int64
 7   transmission  58914 non-null  object
 8   drive         39025 non-null  object
 9   type          43680 non-null  object
 10  seats         52821 non-null  float64
 11  engine_cc     52786 non-null  float64
 12  max_power     52609 non-null  float64
 13  age           58914 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 6.7+ MB

In [ ]:
df['price'].describe()

count          58,911.00
mean       79,528,557.70
std       788,367,096.26
min            40,000.00
25%           350,000.00
50%           550,000.00
75%           869,999.00
max     9,990,000,000.00
Name: price, dtype: float64

In [ ]:
threshold = df['price'].quantile(0.98)

df = df[df['price'] <= threshold]

In [ ]:
df.shape

(57765, 14)

In [ ]:
df.describe()

,price,cylinders,odometer,seats,engine_cc,max_power,age
count,"57,765.00","42,472.00","57,765.00","51,674.00","51,645.00","51,507.00","57,765.00"
mean,"711,781.91",3.79,"60,004.18",5.27,"1,444.99",100.97,8.90
std,"605,923.26",0.52,"48,302.02",0.75,469.64,39.75,3.97
min,"40,000.00",1.00,100.00,0.00,0.00,10.80,0.00
25%,"350,000.00",4.00,"31,406.00",5.00,"1,197.00",74.00,6.00
50%,"540,000.00",4.00,"54,020.00",5.00,"1,248.00",88.50,9.00
75%,"842,000.00",4.00,"80,000.00",5.00,"1,582.00",118.00,12.00
max,"4,500,000.00",16.00,"4,500,088.00",14.00,"6,749.00",769.31,43.00

In [ ]:
df[df['odometer'] == df['odometer'].max()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
38374,gurgaon,1500000,mahindra,bolero,4.00,diesel,4500088,manual,rwd,suv,7.00,"2,523.00",62.10,20

In [ ]:
df[df['age'] == df['age'].max()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
44552,indore,250000,mahindra,willys,NaN,diesel,40000,manual,NaN,suv,6.00,"2,199.00",NaN,43

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.00,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,745000,maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,465000,hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,546000,maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,428000,hyundai,santro,4.00,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df['region'].value_counts(normalize = True).head(10)

region
bangalore   0.13
pune        0.13
new delhi   0.11
gurgaon     0.08
mumbai      0.08
hyderabad   0.05
kolkata     0.03
noida       0.03
ghaziabad   0.03
ahmedabad   0.03
Name: proportion, dtype: float64

In [ ]:
df.isnull().sum()

region          15063
price               0
manufacturer        0
model               0
cylinders       15293
fuel                0
odometer            0
transmission        0
drive           19582
type            15081
seats            6091
engine_cc        6120
max_power        6258
age                 0
dtype: int64

In [ ]:
df['region'].value_counts()

region
bangalore     5744
pune          5533
new delhi     4715
gurgaon       3554
mumbai        3348
              ...
nuh              1
ranaghat         1
biaora           1
balasore         1
sundergarh       1
Name: count, Length: 613, dtype: int64

In [ ]:
df['manufacturer'].value_counts()

manufacturer
maruti                14618
hyundai               11607
honda                  5931
mahindra               3379
tata                   2902
ford                   2192
toyota                 2136
renault                2006
volkswagen             1892
maruti suzuki          1598
skoda                  1498
kia                    1100
mercedes-benz          1072
bmw                    1045
audi                    824
nissan                  748
chevrolet               722
datsun                  582
mg                      441
jeep                    410
fiat                    244
jaguar                  157
land rover              143
volvo                   130
mitsubishi               83
mg motors                80
mahindra ssangyong       51
mini                     45
isuzu                    40
porsche                  27
mahindra renault         13
force                    12
citroen                   8
lexus                     6
hindustan motors          4
bajaj                     3
icml                      3
ferrari                   2
lamborghini               2
premier                   2
bentley                   1
dc                        1
ashok leyland             1
aston martin              1
rolls-royce               1
opel                      1
hummer                    1
Name: count, dtype: int64

In [ ]:
df[df['manufacturer'] == 'bajaj']

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
21515,varanasi,200000,bajaj,re60,1.00,cng,35000,manual,rwd,hatchback,4.00,216.00,10.80,7
21563,bhadohi,280000,bajaj,re60,1.00,cng,1000,manual,rwd,hatchback,4.00,216.00,10.80,4
34926,kalol,275000,bajaj,re60,1.00,cng,40000,manual,rwd,hatchback,4.00,216.00,10.80,7

In [ ]:
df['manufacturer'] = df['manufacturer'].replace('maruti', 'maruti suzuki').replace('mg motors', 'mg').replace('mahindra ssangyong', 'mahindra').replace('mercedes-amg', 'mercedes-benz')

In [ ]:
df['manufacturer'].value_counts()

manufacturer
maruti suzuki       16437
hyundai             11711
honda                5942
mahindra             3431
tata                 2982
ford                 2210
toyota               2146
renault              2006
volkswagen           1892
skoda                1501
mercedes-benz        1262
bmw                  1213
kia                  1100
chevrolet             871
audi                  866
nissan                749
datsun                582
mg                    521
jeep                  417
fiat                  255
land rover            180
jaguar                176
volvo                 153
mitsubishi             84
porsche                48
mini                   47
isuzu                  40
mahindra renault       22
lexus                  17
force                  12
citroen                 8
bentley                 6
hindustan motors        4
maserati                3
ferrari                 3
bajaj                   3
icml                    3
premier                 2
rolls-royce             2
lamborghini             2
ashok leyland           1
dc                      1
aston martin            1
opel                    1
hummer                  1
Name: count, dtype: int64

In [ ]:
counts = df['manufacturer'].value_counts()

df['manufacturer'] = df['manufacturer'].apply(
    lambda x: 'others' if counts[x] < 5 else x
)

In [ ]:
df['manufacturer'].value_counts()

manufacturer
maruti suzuki       16437
hyundai             11711
honda                5942
mahindra             3431
tata                 2982
ford                 2210
toyota               2146
renault              2006
volkswagen           1892
skoda                1501
mercedes-benz        1262
bmw                  1213
kia                  1100
chevrolet             871
audi                  866
nissan                749
datsun                582
mg                    521
jeep                  417
fiat                  255
land rover            180
jaguar                176
volvo                 153
mitsubishi             84
porsche                48
mini                   47
isuzu                  40
others                 27
mahindra renault       22
lexus                  17
force                  12
citroen                 8
bentley                 6
Name: count, dtype: int64

In [ ]:
df['model'].value_counts().head(50)

model
city             2893
i20              2429
swift            2377
wagon r          2239
swift dzire      2084
i10              1537
verna            1450
baleno           1445
creta            1422
amaze            1277
grand i10        1260
ciaz             1166
xuv500           1074
ecosport         1037
alto              979
kwid              964
polo              914
ertiga            836
innova            804
celerio           789
alto 800          732
seltos            679
vento             675
vitara brezza     674
rapid             660
tiago             649
figo              636
jazz              632
nexon             616
duster            589
scorpio           588
grand             569
venue             455
alto k10          437
eeco              425
fortuner          407
compass           403
c-class           365
eon               361
thar              354
santro            350
santro xing       344
xcent             343
hector            336
e-class           334
beat              323
wr-v              323
sonet             315
bolero            310
brio              290
Name: count, dtype: int64

In [ ]:
df['model'] = df['model'].str.replace(r'\b(19|20)\d{2}\b', '', regex=True).str.strip()

In [ ]:
df['model'].value_counts().head(50)

model
city             2884
i20              2429
swift            2375
wagon r          2163
swift dzire      2083
i10              1518
verna            1450
baleno           1445
creta            1422
amaze            1277
grand i10        1260
ciaz             1165
xuv500           1074
ecosport         1036
kwid              964
alto              929
polo              914
ertiga            836
innova            804
celerio           789
alto 800          732
seltos            679
vento             675
vitara brezza     674
rapid             660
tiago             649
jazz              632
figo              631
nexon             616
duster            589
scorpio           588
grand             569
venue             455
alto k10          437
eeco              425
fortuner          406
compass           403
eon               361
thar              354
c-class           351
xcent             343
santro            340
hector            336
wr-v              323
sonet             315
beat              314
bolero            309
e-class           300
brio              290
ignis             289
Name: count, dtype: int64

In [ ]:
df['cylinders'].value_counts()

cylinders
4.00     31845
3.00      9965
6.00       376
5.00       118
2.00        74
7.00        55
8.00        29
1.00         5
10.00        2
12.00        2
16.00        1
Name: count, dtype: int64

In [ ]:
df['fuel'].value_counts()

fuel
petrol        34208
diesel        22705
cng            1581
lpg             247
electric        132
petrol+cng       25
hybrid           16
Name: count, dtype: int64

In [ ]:
df['odometer'] = df['odometer'].astype('int')

In [ ]:
df['transmission'].value_counts()

transmission
manual       44244
automatic    13521
Name: count, dtype: int64

In [ ]:
df['drive'].value_counts()

drive
fwd                                         32423
rwd                                          2152
awd                                           902
2wd                                           610
4wd                                           594
2 wd                                          361
4x2                                           294
4x4                                           226
fwd                                           216
front wheel drive                             166
two wheel drive                                96
all wheel drive                                32
rear wheel drive with esp                      29
two whhel drive                                25
permanent all-wheel drive quattro              21
rwd(with mtt)                                  14
4 wd                                            7
rear-wheel drive with esp                       7
all-wheel drive with electronic traction        5
four whell drive                                2
3                                               1
Name: count, dtype: int64

In [ ]:
df[df['drive'] == '3']

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
43931,vadodara,1150000,tata,nexon,3.00,petrol,527,automatic,3,suv,5.00,"1,199.00",118.36,4

In [ ]:
df['drive'] = df['drive'].replace('3', 'fwd')

In [ ]:
df[df['drive'] == '3']

Empty DataFrame
Columns: [region, price, manufacturer, model, cylinders, fuel, odometer, transmission, drive, type, seats, engine_cc, max_power, age]
Index: []

In [ ]:
df['drive'].value_counts()

drive
fwd                                         32832
rwd                                          2319
awd                                          1078
2wd                                           647
4wd                                           626
2 wd                                          368
4x2                                           295
4x4                                           228
fwd                                           216
front wheel drive                             175
two wheel drive                                98
all wheel drive                                32
rear wheel drive with esp                      29
two whhel drive                                26
permanent all-wheel drive quattro              21
rwd(with mtt)                                  14
4 wd                                            7
rear-wheel drive with esp                       7
all-wheel drive with electronic traction        5
four whell drive                                2
Name: count, dtype: int64

In [ ]:
df['drive'] = df['drive'].str.strip()

In [ ]:
df['drive'].value_counts()

drive
fwd                                         33048
rwd                                          2319
awd                                          1078
2wd                                           647
4wd                                           626
2 wd                                          368
4x2                                           295
4x4                                           228
front wheel drive                             175
two wheel drive                                98
all wheel drive                                32
rear wheel drive with esp                      29
two whhel drive                                26
permanent all-wheel drive quattro              21
rwd(with mtt)                                  14
4 wd                                            7
rear-wheel drive with esp                       7
all-wheel drive with electronic traction        5
four whell drive                                2
Name: count, dtype: int64

In [ ]:
df['drive'] = df['drive'].replace('front wheel drive', 'fwd').replace('two wheel drive', '2wd').replace('all wheel drive', 'awd').replace('rear wheel drive with esp', 'rwd').replace('2 wd', '2wd').replace('two whhel drive', '2wd').replace('rwd(with mtt)', 'rwd').replace('4 wd', '4wd').replace('rear-wheel drive with esp', 'rwd').replace('all-wheel drive with electronic traction', 'awd').replace('four whell drive', '4wd')

In [ ]:
df['drive'] = df['drive'].replace('permanent all-wheel drive quattro', 'awd')

In [ ]:
df['drive'].value_counts()

drive
fwd    32806
rwd     2202
2wd     1092
awd      960
4wd      603
4x2      294
4x4      226
Name: count, dtype: int64

In [ ]:
df['type'].value_counts()

type
hatchback          17202
sedan              11448
suv                11444
muv                 2008
minivans             368
crossover             68
luxury vehicles       68
pickup trucks         47
convertibles          11
coupe                 10
wagon                  6
hybrids                3
mpv                    1
Name: count, dtype: int64

In [ ]:
df['seats'].value_counts()

seats
5.00     45261
7.00      5646
8.00       735
6.00       518
4.00       484
9.00        94
2.00        43
10.00       23
0.00        13
13.00        2
14.00        2
Name: count, dtype: int64

In [ ]:
df['engine_cc'].head(20)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: engine_cc, dtype: float64

In [ ]:
df['engine_cc'] = df['engine_cc'].astype(str).str.replace(',', '')

In [ ]:
df['engine_cc'].sample(30)

18505    1968.0
21132     796.0
10392    2523.0
25844    1498.0
53098    1198.0
50186    1497.0
55757    1582.0
5936        nan
30100    2231.0
26823    1199.0
22585       0.0
14606    2179.0
18552    1598.0
37103    1199.0
55711    1120.0
43807    1197.0
48461     998.0
17462    1396.0
29754    1199.0
33195    1451.0
6165     1582.0
46902    1197.0
18620    1248.0
10055    1197.0
44384    2179.0
38183    2179.0
40505    2179.0
40823    1120.0
58056     796.0
26322    1196.0
Name: engine_cc, dtype: object

In [ ]:
df['max_power'].sample(20)

41573    88.70
17982   190.00
767        NaN
37945    83.10
15489    98.59
5553       NaN
26850    88.80
41113   130.00
24825    53.30
47828   115.05
12448   121.00
4795       NaN
50359    86.80
29299   107.30
35548    82.00
35417    88.73
20765   108.45
21700    55.92
26794   103.60
21645    82.00
Name: max_power, dtype: float64

In [ ]:
df['max_power'] = df['max_power'].str.split(' ').str.get(0)

In [ ]:
df['max_power'] = df['max_power'].str.extract(r'(\d+\.?\d*)')

In [ ]:
df['max_power'] = df['max_power'].astype('float')

In [ ]:
df['max_power'].sample(20)

7331    113.40
49815    80.00
49096    74.00
44683   120.00
47120   126.20
10988   108.00
41698   103.25
14953   117.30
49584    78.90
40359    81.86
49245    81.83
1059       NaN
19107    67.04
36067    82.00
24406   168.50
48883    81.80
20072    81.80
23737    73.00
22507    25.40
7915     67.10
Name: max_power, dtype: float64

In [ ]:
df['age'].value_counts()

age
9     5423
8     5406
5     5157
7     4740
10    4650
6     4485
4     4415
11    4404
12    4070
13    3048
3     2436
14    2341
15    1999
16    1601
2     1303
17    1105
18     563
1      241
19     155
20      91
21      49
22      32
23      17
24      12
25       7
0        3
29       2
26       2
30       2
27       1
37       1
32       1
40       1
43       1
28       1
Name: count, dtype: int64

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.00,petrol,20979,manual,fwd,hatchback,NaN,nan,NaN,5
1,agra,745000,maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback,NaN,nan,NaN,3
2,agra,465000,hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback,NaN,nan,NaN,7
3,agra,546000,maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback,NaN,nan,NaN,3
4,agra,428000,hyundai,santro,4.00,cng,102049,manual,fwd,hatchback,NaN,nan,NaN,5

In [ ]:
df.to_csv('cars_data_cleaned_1.csv', index = False)